import { defineUnit, FUNDS_RESOURCE, type UnitDef, type WeaponDef } from '@empire/battle-engine';
import { ANCIENT_EMPIRES_WEAPONS } from './weapons';

const weapons = new Map<string, WeaponDef>(ANCIENT_EMPIRES_WEAPONS.map((weapon) => [weapon.id, weapon]));
const unit = (def: Partial<UnitDef> & { id: string; name: string; weapons: string[] }) =>
  defineUnit({
    movementClass: 'foot',
    armorClass: 'light',
    value: def.value ?? 100,
    recruitCosts: def.recruitCosts ?? [{ resource: FUNDS_RESOURCE, amount: def.value ?? 100 }],
    ...def,
  }, weapons);

export const ANCIENT_EMPIRES_UNITS: readonly UnitDef[] = [
  unit({
    id: 'soldier',
    name: '剑士',
    weapons: ['soldier_sword', 'soldier_javelin'],
    value: 100,
    maxHp: 100,
    defense: 0.1,
    movement: 3,
    armorClass: 'light',
    blurb: '廉价的战线核心，能占领城镇。',
    tags: ['infantry'],
  }),
  unit({
    id: 'archer',
    name: '弓箭手',
    weapons: ['archer_bow'],
    value: 150,
    maxHp: 80,
    movement: 3,
    armorClass: 'unarmored',
    blurb: '隔一格射击不吃近战反击，克制飞行单位。',
    tags: ['infantry', 'ranged'],
  }),
  unit({
    id: 'rogue',
    name: '刺客',
    weapons: ['rogue_blades'],
    value: 200,
    maxHp: 80,
    movement: 5,
    armorClass: 'unarmored',
    blurb: '机动极高，专杀无甲的法师与弓手。',
    tags: ['infantry'],
  }),
  unit({
    id: 'cleric',
    name: '牧师',
    weapons: ['cleric_staff'],
    value: 250,
    maxHp: 70,
    movement: 3,
    armorClass: 'unarmored',
    abilities: ['heal', 'attack', 'capture', 'wait'],
    blurb: '治疗相邻友军 30 点生命，自身脆弱。',
    tags: ['infantry', 'support'],
  }),
  unit({
    id: 'mage',
    name: '法师',
    weapons: ['mage_bolt', 'mage_overcharge', 'mage_meteor'],
    value: 300,
    maxHp: 70,
    movement: 3,
    armorClass: 'unarmored',
    blurb: '魔法伤害无视重甲，是攻城的答案；陨石术需要咏唱两个行动轮。',
    tags: ['infantry', 'ranged'],
  }),
  unit({
    id: 'knight',
    name: '骑士',
    weapons: ['knight_sword', 'knight_charge', 'heroic_breakthrough'],
    value: 350,
    maxHp: 110,
    defense: 0.15,
    movement: 6,
    movementClass: 'mounted',
    armorClass: 'heavy',
    abilities: ['attack', 'wait'],
    blurb: '六格突进的重锤，无法占领城镇，怕魔法。',
    tags: ['cavalry'],
  }),
  unit({
    id: 'ogre',
    name: '巨魔',
    weapons: ['ogre_club'],
    value: 400,
    maxHp: 150,
    defense: 0.25,
    movement: 3,
    movementClass: 'heavy',
    armorClass: 'heavy',
    abilities: ['attack', 'wait'],
    defaultReaction: 'support',
    blurb: '血厚甲厚的攻坚肉盾，走不上山地。',
    tags: ['monster'],
  }),
  unit({
    id: 'ballista',
    name: '弩车',
    weapons: ['ballista_bolt'],
    value: 350,
    maxHp: 70,
    movement: 2,
    movementClass: 'heavy',
    armorClass: 'light',
    abilities: ['attack', 'wait'],
    blurb: '攻城器械：必须静止开火，绝不会被反击。',
    tags: ['siege', 'ranged'],
  }),
  unit({
    id: 'dragon',
    name: '巨龙',
    weapons: ['dragon_breath'],
    value: 700,
    maxHp: 160,
    defense: 0.2,
    movement: 5,
    movementClass: 'flying',
    armorClass: 'flying',
    abilities: ['attack', 'wait'],
    vision: 4,
    blurb: '无视地形飞行，唯一弱点是弓箭。',
    tags: ['monster', 'flying'],
  }),
];
