import { defineWeapon as defineWeaponBase, type WeaponDef } from '@empire/battle-engine';

const weapon = (
  definition: Partial<WeaponDef> & Pick<WeaponDef, 'id' | 'name' | 'power'>,
): WeaponDef => defineWeaponBase({ damageType: 'slash', ...definition });

/**
 * Candidate 01 owns its combat vocabulary.  The values intentionally stay in
 * the same 30-60 band as the engine reference pack so mixed encounters remain
 * predictable while every faction still has a distinct tactical answer.
 */
export const CANDIDATE_01_WEAPONS: readonly WeaponDef[] = [
  weapon({ id: 'c01.border-blade', name: '边境长剑', power: 39, tags: ['melee'] }),
  weapon({ id: 'c01.civilian-tool', name: '随身工具', power: 8, damageType: 'blunt', canCounter: false, tags: ['improvised'] }),
  weapon({
    id: 'c01.gray-oath',
    name: '灰誓裂阵',
    power: 52,
    cooldown: 3,
    area: 'cross1',
    canCounter: false,
    hitEffects: [{ type: 'addStatus', status: 'shaken', duration: 1 }],
    tags: ['melee', 'signature', 'command'],
  }),
  weapon({ id: 'c01.guard-spear', name: '灰旗长枪', power: 37, damageType: 'pierce', tags: ['melee', 'formation'] }),
  weapon({
    id: 'c01.legion-spear',
    name: '军团拒马枪',
    power: 42,
    damageType: 'pierce',
    bonuses: [{ targetTag: 'cavalry', multiplier: 1.35, reason: '拒马枪阵' }],
    tags: ['melee', 'formation', 'anti-cavalry'],
  }),
  weapon({ id: 'c01.knight-lance', name: '骑士战枪', power: 50, damageType: 'pierce', tags: ['melee', 'mounted'] }),
  weapon({
    id: 'c01.knight-charge',
    name: '破阵冲锋',
    power: 60,
    cooldown: 2,
    canCounter: false,
    hitEffects: [{ type: 'forcedMove', mode: 'push', distance: 1, collisionDamage: 8 }],
    tags: ['melee', 'mounted', 'charge'],
  }),
  weapon({
    id: 'c01.longbow',
    name: '银木长弓',
    power: 38,
    damageType: 'pierce',
    minRange: 2,
    maxRange: 3,
    lineOfSight: 'direct',
    bonuses: [{ targetTag: 'flying', multiplier: 1.4, reason: '银木对空箭' }],
    tags: ['ranged', 'projectile'],
  }),
  weapon({
    id: 'c01.ranger-bow',
    name: '灰境猎弓',
    power: 35,
    damageType: 'pierce',
    maxRange: 3,
    lineOfSight: 'arc',
    tags: ['ranged', 'projectile', 'scout'],
  }),
  weapon({ id: 'c01.lantern-staff', name: '守墓灯杖', power: 24, damageType: 'magic', maxRange: 2, tags: ['arcane', 'support'] }),
  weapon({
    id: 'c01.oath-dispel',
    name: '断誓灯火',
    power: 43,
    damageType: 'magic',
    maxRange: 2,
    cooldown: 2,
    bonuses: [
      { targetTag: 'undead', multiplier: 1.4, reason: '归还亡者姓名' },
      { targetTag: 'oathbound', multiplier: 1.3, reason: '切断控制誓文' },
    ],
    hitEffects: [{ type: 'removeStatus', status: 'c01.oath-controlled' }],
    tags: ['arcane', 'support', 'signature'],
  }),
  weapon({ id: 'c01.engineer-hammer', name: '工兵锤', power: 32, damageType: 'blunt', tags: ['melee', 'engineer'] }),
  weapon({
    id: 'c01.satchel-charge',
    name: '破门火药',
    power: 56,
    damageType: 'blunt',
    maxRange: 2,
    area: 'cross1',
    cooldown: 3,
    canCounter: false,
    bonuses: [{ targetTag: 'building', multiplier: 1.6, reason: '工兵爆破' }],
    tags: ['ranged', 'siege', 'engineer'],
  }),
  weapon({ id: 'c01.rune-hammer', name: '山炉符文锤', power: 44, damageType: 'blunt', tags: ['melee', 'rune'] }),
  weapon({
    id: 'c01.forge-burst',
    name: '炉心震击',
    power: 50,
    damageType: 'magic',
    maxRange: 2,
    cooldown: 2,
    hitEffects: [{ type: 'addStatus', status: 'armor_down', duration: 2 }],
    tags: ['arcane', 'rune'],
  }),
  weapon({ id: 'c01.wolf-spear', name: '荒原骑矛', power: 45, damageType: 'pierce', tags: ['melee', 'mounted'] }),
  weapon({ id: 'c01.undead-blade', name: '回声残刃', power: 34, damageType: 'slash', tags: ['melee', 'undead'] }),
  weapon({ id: 'c01.ghost-touch', name: '失名之触', power: 36, damageType: 'magic', maxRange: 2, tags: ['arcane', 'undead'] }),
  weapon({
    id: 'c01.inquisitor-flame',
    name: '审判誓火',
    power: 44,
    damageType: 'magic',
    maxRange: 2,
    area: 'cross1',
    cooldown: 2,
    hitEffects: [{ type: 'addStatus', status: 'silenced', duration: 1 }],
    tags: ['arcane', 'ranged'],
  }),
  weapon({
    id: 'c01.golem-slam',
    name: '石躯重击',
    power: 49,
    damageType: 'blunt',
    hitEffects: [{ type: 'forcedMove', mode: 'push', distance: 1, collisionDamage: 10 }],
    tags: ['melee', 'impact'],
  }),
  weapon({
    id: 'c01.ballista',
    name: '城防重弩',
    power: 55,
    damageType: 'pierce',
    minRange: 2,
    maxRange: 4,
    moveAndAttack: false,
    lineOfSight: 'direct',
    canCounter: false,
    bonuses: [{ targetTag: 'building', multiplier: 1.45, reason: '攻城重弩' }],
    tags: ['ranged', 'siege'],
  }),
  weapon({ id: 'c01.oath-bolt', name: '誓火弹', power: 41, damageType: 'magic', maxRange: 2, tags: ['arcane', 'ranged'] }),
  weapon({
    id: 'c01.dragon-breath',
    name: '盟约龙息',
    power: 58,
    damageType: 'magic',
    maxRange: 2,
    area: 'line',
    cooldown: 1,
    tags: ['breath', 'arcane', 'signature'],
  }),
  weapon({
    id: 'c01.colossus-sweep',
    name: '墓园横扫',
    power: 54,
    damageType: 'blunt',
    area: 'ring1',
    cooldown: 2,
    tags: ['melee', 'undead', 'impact'],
  }),
];
