import { defineWeapon as defineWeaponBase } from '../../core/content-builders';
import { MOMENTUM_RESOURCE, WEAPON_USES_RESOURCE } from '../../core/resources';
import type { WeaponDef } from '../../core/types';

const defineWeapon = (definition: Partial<WeaponDef> & Pick<WeaponDef, 'id' | 'name' | 'power'>): WeaponDef =>
  defineWeaponBase({ damageType: 'slash', ...definition });

export const ANCIENT_EMPIRES_WEAPONS: readonly WeaponDef[] = [
  defineWeapon({ id: 'soldier_sword', name: '长剑', power: 38, tags: ['melee'] }),
  defineWeapon({
    id: 'soldier_javelin',
    name: '投枪',
    power: 26,
    damageType: 'pierce',
    minRange: 2,
    maxRange: 2,
    resources: { [WEAPON_USES_RESOURCE]: { current: 2, capacity: 2 } },
    resourceCosts: [{ resource: WEAPON_USES_RESOURCE, subject: 'weapon', amount: 1 }],
    canCounter: false,
    tags: ['ranged', 'projectile', 'limited'],
  }),
  defineWeapon({
    id: 'archer_bow',
    name: '短弓',
    power: 34,
    damageType: 'pierce',
    maxRange: 2,
    bonuses: [{ targetTag: 'flying', multiplier: 1.4, reason: '弓箭对空' }],
    tags: ['ranged', 'projectile'],
  }),
  defineWeapon({
    id: 'rogue_blades',
    name: '淬毒双刃',
    power: 46,
    damageType: 'pierce',
    bonuses: [
      { targetTag: 'support', multiplier: 1.3, reason: '刺杀辅助单位' },
      { targetTag: 'ranged', multiplier: 1.25, reason: '切入远程后排' },
    ],
    hitEffects: [{ type: 'addStatus', status: 'poisoned', duration: 2 }],
    tags: ['melee'],
  }),
  defineWeapon({ id: 'cleric_staff', name: '法杖', power: 18, damageType: 'blunt', tags: ['melee'] }),
  defineWeapon({
    id: 'mage_bolt',
    name: '魔法弹',
    power: 42,
    damageType: 'magic',
    maxRange: 2,
    tags: ['ranged', 'arcane'],
  }),
  defineWeapon({
    id: 'mage_overcharge',
    name: '奥术过载',
    power: 56,
    damageType: 'magic',
    maxRange: 2,
    cooldown: 2,
    area: 'cross1',
    hitEffects: [{ type: 'addStatus', status: 'armor_down', duration: 2 }],
    tags: ['ranged', 'arcane', 'cooldown'],
  }),
  defineWeapon({ id: 'knight_sword', name: '骑士剑', power: 48, tags: ['melee', 'mounted'] }),
  defineWeapon({
    id: 'knight_charge',
    name: '骑士冲锋',
    power: 60,
    cooldown: 2,
    canCounter: false,
    tags: ['melee', 'mounted', 'charge', 'cooldown'],
  }),
  defineWeapon({
    id: 'heroic_breakthrough',
    name: '战意裂阵',
    power: 72,
    area: 'cross1',
    cooldown: 3,
    canCounter: false,
    resourceRequirements: [{ resource: MOMENTUM_RESOURCE, subject: 'unit', amount: 120 }],
    resourceCosts: [{ resource: MOMENTUM_RESOURCE, subject: 'unit', amount: 20 }],
    tags: ['melee', 'mounted', 'signature', 'cooldown'],
  }),
  defineWeapon({ id: 'ogre_club', name: '巨棒', power: 52, damageType: 'blunt', tags: ['melee', 'impact'] }),
  defineWeapon({
    id: 'ballista_bolt',
    name: '重弩',
    power: 58,
    damageType: 'pierce',
    minRange: 2,
    maxRange: 3,
    moveAndAttack: false,
    lineOfSight: 'direct',
    bonuses: [{ targetTag: 'building', multiplier: 1.5, reason: '攻城武器' }],
    tags: ['ranged', 'siege'],
  }),
  defineWeapon({
    id: 'dragon_breath',
    name: '龙息',
    power: 62,
    damageType: 'magic',
    maxRange: 2,
    area: 'line',
    tags: ['breath', 'arcane'],
  }),
];
